### ISSUE TITLE
the npm setup commands are failing when I attempt to run them at root. 

### ISSUE THREAD

**Issue by spstratis** [bradleygore/nativescript-materialdropdownlist#2]
I'm attempting to try the demo build but am running into problems when I try to run the "npm run setup" command.  Below is the info from the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild nativescript-materialdropdownlist@1.0.14
6 info build nativescript-materialdropdownlist@1.0.14
7 verbose unsafe-perm in lifecycle true
8 info nativescript-materialdropdownlist@1.0.14 Failed to exec build script
9 verbose stack Error: nativescript-materialdropdownlist@1.0.14 build: `tsc`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid nativescript-materialdropdownlist@1.0.14
11 verbose cwd /Users/stevenstratis/Documents/Developer/material-dropdown/nativescript-materialdropdownlist
12 error Darwin 15.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
14 error node v4.4.2
15 error npm  v2.15.0
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error nativescript-materialdropdownlist@1.0.14 build: `tsc`
20 error spawn ENOENT
21 error Failed at the nativescript-materialdropdownlist@1.0.14 build script 'tsc'.
21 error This is most likely a problem with the nativescript-materialdropdownlist package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     tsc
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs nativescript-materialdropdownlist
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls nativescript-materialdropdownlist
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by bradleygore** [comment]
@spstratis Do you have all the node modules installed (i.e. did you run `npm install`) and it looks like it's erroring on tsc command - that is the typescript compiler. Are you able to run `tsc` by itself? If not, you may need to install it.

**Comment by bradleygore** [comment]
Have had no response, closing.

**Comment by spstratis** [comment]
@bradleygore Sorry thought I responded to this, I just installed the plugin into another project and used it there rather than playing around with the demo. So far it's working great.

**Comment by bradleygore** [comment]
@spstratis Awesome - glad to hear :smile:
