### ISSUE TITLE
demo failure on iOS with NativeScript 2.3 and Angular 2.0

### ISSUE THREAD

**Issue by andy-tai** [bradleygore/nativescript-materialdropdownlist#3]
Hi, I use the latest master branch and pull down the repo, and try to run the demo on an iOS simulator, on a Mac host.  The drop down menus do not work, and the terminal shows these erro log:
Signing Identity:     "-"

```
/usr/bin/codesign --force --sign - --timestamp=none /Users/atai/native_script_works/nativescript-materialdropdownlist.git/demo/platforms/ios/build/emulator/demo.app
```

*\* BUILD SUCCEEDED **

Project successfully built
Successfully deployed on device with identifier '4CB95E45-B758-4000-85C5-5D8165CFA3B6'.
Oct 29 13:56:59 Li-Chengs-Mini demo[69295]: objc[69295]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x119318910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x119142210). One of the two will be used. Which one is undefined.
Oct 29 13:57:01 Li-Chengs-Mini demo[69295]: assertion failed: 16A323 14A345: libxpc.dylib + 62597 [37A9DF49-35C1-3D93-B854-B35CACF0100F]: 0x7d

the menus will not drop down when clicked on

The same configuration works fine on Android emulator running Android 6

**Comment by bradleygore** [comment]
Hey @andy-tai - I've never tested this with angular 2, and believe I was on NS 2.0 when I built it. I'm not currently actively developing with NS at the moment, hoping to pick it back up in the next 6 or so months. In the meantime, I honestly don't know when I'll be able to get to this. PRs are welcome :)

**Comment by andy-tai** [comment]
Ok I will try to see if I can do anything with this.  No promises but I will play with it.

**Comment by bradleygore** [comment]
Hey @andy-tai - I've dug into this a lot this weekend and found that the approach I took just doesn't work on iOS. I've opened issue #4 outlining the exact cause of the problem. I apologize for any inconvenience. I'll also be reaching out to the NativeScript team to get their thoughts - would be awesome if we could add arbitrary number of `AbsoluteLayout`s to a `Page`.

**Comment by andy-tai** [comment]
sure.  That is good.  Thanks
